theme: jekyll-theme-tactile
title: "Welcome to Numpy_Quickstart"
description: Numpy Quicksatrt is a Github repository based project which implements all the basic numpy practices form numpy.org itself and incorporates basic numpy tutorials 
